### ISSUE TITLE
Config file break

### ISSUE THREAD

**Issue by Saran-nns** [Saran-nns/sorn#13]
Traceback (most recent call last):
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Network_Config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\site-packages\sorn\__init__.py", line 1, in <module>
    from .sorn import Simulator, Trainer
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\site-packages\sorn\sorn.py", line 19, in <module>
    class Sorn(object):
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\site-packages\sorn\sorn.py", line 28, in Sorn
    nu = int(parser.get('Network_Config', 'Nu'))  # Number of input units
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\saran\Anaconda3\envs\tfgpu\lib\configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Network_Config'

**Comment by Saran-nns** [comment]
absolute path issue resolved @ 0.3.6

**Comment by Saran-nns** [comment]
config is not reachable @ utils and sorn modules
